# ~/.termia/shell/termia.zsh
# Auto-generated by Termia - do not edit manually
# Sourced inside the wrapped shell to provide tui/tai functions and command hooks

# Only activate inside the wrapper
[[ -z "$TERMIA_WRAPPED" ]] && return
[[ -n "$TERMIA_INTEGRATION_LOADED" ]] && return
export TERMIA_INTEGRATION_LOADED=1

# ─── Injected shell functions ───────────────────────────────

tui() {
    local cd_file=""
    if command -v mktemp >/dev/null 2>&1; then
        cd_file="$(mktemp "${TERMIA_SHELL_DIR:-/tmp}/termia-cd.XXXXXX")"
    else
        cd_file="${TERMIA_SHELL_DIR:-/tmp}/termia-cd.$$"
        : >"$cd_file"
    fi
    TERMIA_CD_FILE="$cd_file" "${TERMIA_BIN:-termia}" tui "$@"
    local exit_code=$?
    if [[ -n "$cd_file" && -s "$cd_file" ]]; then
        local new_dir
        new_dir="$(cat "$cd_file")"
        if [[ -n "$new_dir" ]]; then
            builtin cd -- "$new_dir" 2>/dev/null || true
        fi
    fi
    [[ -n "$cd_file" ]] && rm -f "$cd_file"
    return $exit_code
}

tai() {
    "${TERMIA_BIN:-termia}" tai "$@"
}

# ─── Command boundary markers ──────────────────────────────
# NOTE: No external dependencies (no jq, no uuidgen).
# UUID generated by wrapper via marker FD response, or using
# shell built-in $RANDOM + timestamp for lightweight ID.

_termia_cmd_id=""
_termia_prompt_hint=""
_termia_prompt_base=""

_termia_osc133() {
    local seq="$1"
    printf '\033]133;%s\007' "$seq"
}

_termia_dealias() {
    local cmdline="$1"
    local first="${cmdline%% *}"
    local alias_def

    alias_def=$(alias "$first" 2>/dev/null) || { printf "%s" "$cmdline"; return; }
    alias_def="${alias_def#alias $first=}"
    alias_def="${alias_def#\'}"
    alias_def="${alias_def%\'}"

    if [[ "$alias_def" == "$first"* ]]; then
        local rest="${alias_def#"$first"}"
        if [[ -n "$rest" && "$cmdline" == "$first$rest"* ]]; then
            printf "%s%s" "$first" "${cmdline#"$first$rest"}"
            return
        fi
    fi

    printf "%s" "$cmdline"
}

_termia_update_prompt_hint() {
    local count_file="${TERMIA_PENDING_PROMPTS_COUNT:-}"
    local count=""
    if [[ -n "$count_file" && -f "$count_file" ]]; then
        count=$(< "$count_file")
    fi
    if [[ "$count" == <-> ]] && (( count > 0 )); then
        _termia_prompt_hint="🔔${count} "
    else
        _termia_prompt_hint=""
    fi
    if [[ -z "$_termia_prompt_base" ]]; then
        _termia_prompt_base="$PROMPT"
    fi
    PROMPT="${_termia_prompt_hint}${_termia_prompt_base}"
}

_termia_import_history_queue() {
    [[ -n "$TERMIA_NO_RECORD" ]] && return
    local queue="${TERMIA_HISTORY_QUEUE:-}"
    [[ -z "$queue" ]] && return
    [[ ! -s "$queue" ]] && return

    local tmp="${queue}.$$"
    if mv "$queue" "$tmp" 2>/dev/null; then
        : > "$queue" 2>/dev/null
    else
        tmp="$queue"
    fi

    local line
    while IFS= read -r line || [[ -n "$line" ]]; do
        print -s -- "$line"
    done < "$tmp"

    if [[ "$tmp" != "$queue" ]]; then
        rm -f "$tmp"
    else
        : > "$queue" 2>/dev/null
    fi
}

_termia_preexec() {
    # Skip if in privacy mode
    [[ -n "$TERMIA_NO_RECORD" ]] && return
    if [[ -n "$TERMIA_INTERNAL" ]] && [[ -n "$TERMIA_INTEGRATION_LOADED" ]]; then
        return
    fi
    if [[ -n "$TERMIA_INTERNAL_PATTERN" ]] && [[ "$1" =~ $TERMIA_INTERNAL_PATTERN ]]; then
        return
    fi

    # Generate lightweight command ID (no uuidgen dependency)
    _termia_cmd_id="${EPOCHREALTIME:-$(date +%s)}-$$-${RANDOM}"
    local command_text="$(_termia_dealias "$1")"

    # Write marker to FD 3 (passed by wrapper)
    # Pure shell string — no jq dependency
    if [[ -n "$TERMIA_MARKER_FD" ]]; then
        printf '{"cmd_id":"%s","phase":"start","command":"%s","cwd":"%s","ts":%s}\n' \
            "$_termia_cmd_id" \
            "${command_text//\"/\\\"}" \
            "$PWD" \
            "${EPOCHREALTIME:-$(date +%s)}" \
            >&${TERMIA_MARKER_FD}
    fi

    _termia_osc133 "B"
}

_termia_precmd() {
    local exit_code=$?

    _termia_update_prompt_hint

    [[ -n "$TERMIA_NO_RECORD" ]] && { _termia_cmd_id=""; return; }
    if [[ -n "$TERMIA_INTERNAL" ]] && [[ -n "$TERMIA_INTEGRATION_LOADED" ]]; then
        unset TERMIA_INTERNAL
        _termia_cmd_id=""
        return
    fi

    _termia_import_history_queue
    fc -W

    [[ -z "$_termia_cmd_id" ]] && return

    if [[ -n "$TERMIA_MARKER_FD" ]]; then
        printf '{"cmd_id":"%s","phase":"end","exit_code":%d,"ts":%s}\n' \
            "$_termia_cmd_id" \
            "$exit_code" \
            "${EPOCHREALTIME:-$(date +%s)}" \
            >&${TERMIA_MARKER_FD}
    fi

    _termia_osc133 "D;$exit_code"

    _termia_cmd_id=""
}

# ─── Register hooks ────────────────────────────────────────

autoload -Uz add-zsh-hook
add-zsh-hook preexec _termia_preexec
add-zsh-hook precmd _termia_precmd

_termia_osc133 "A"

# ─── Welcome message (only on first launch) ────────────────

[[ "$TERMIA_WELCOME" == "1" ]] && echo "🚀 Termia active! Type 'tui' for history, 'tai' for AI help."
