# ~/.termia/shell/termia.zsh
# Auto-generated by Termia - do not edit manually
# Sourced inside the wrapped shell to provide tui/tai functions and command hooks

# Only activate inside the wrapper
[[ -z "$TERMIA_WRAPPED" ]] && return
[[ -n "$TERMIA_INTEGRATION_LOADED" ]] && return
export TERMIA_INTEGRATION_LOADED=1

# ─── Injected shell functions ───────────────────────────────

tui() {
    "${TERMIA_BIN:-termia}" tui "$@"
}

tai() {
    "${TERMIA_BIN:-termia}" tai "$@"
}

# ─── Command boundary markers ──────────────────────────────
# NOTE: No external dependencies (no jq, no uuidgen).
# UUID generated by wrapper via marker FD response, or using
# shell built-in $RANDOM + timestamp for lightweight ID.

_termia_cmd_id=""

_termia_osc133() {
    local seq="$1"
    printf '\033]133;%s\007' "$seq"
}

_termia_dealias() {
    local cmdline="$1"
    local first="${cmdline%% *}"
    local alias_def

    alias_def=$(alias "$first" 2>/dev/null) || { printf "%s" "$cmdline"; return; }
    alias_def="${alias_def#alias $first=}"
    alias_def="${alias_def#\'}"
    alias_def="${alias_def%\'}"

    if [[ "$alias_def" == "$first"* ]]; then
        local rest="${alias_def#"$first"}"
        if [[ -n "$rest" && "$cmdline" == "$first$rest"* ]]; then
            printf "%s%s" "$first" "${cmdline#"$first$rest"}"
            return
        fi
    fi

    printf "%s" "$cmdline"
}

_termia_preexec() {
    # Skip if in privacy mode
    [[ -n "$TERMIA_NO_RECORD" ]] && return
    if [[ -n "$TERMIA_INTERNAL" ]] && [[ -n "$TERMIA_INTEGRATION_LOADED" ]]; then
        return
    fi
    if [[ -n "$TERMIA_INTERNAL_PATTERN" ]] && [[ "$1" =~ $TERMIA_INTERNAL_PATTERN ]]; then
        return
    fi

    # Generate lightweight command ID (no uuidgen dependency)
    _termia_cmd_id="${EPOCHREALTIME:-$(date +%s)}-$$-${RANDOM}"
    local command_text="$(_termia_dealias "$1")"

    # Write marker to FD 3 (passed by wrapper)
    # Pure shell string — no jq dependency
    if [[ -n "$TERMIA_MARKER_FD" ]]; then
        printf '{"cmd_id":"%s","phase":"start","command":"%s","cwd":"%s","ts":%s}\n' \
            "$_termia_cmd_id" \
            "${command_text//\"/\\\"}" \
            "$PWD" \
            "${EPOCHREALTIME:-$(date +%s)}" \
            >&${TERMIA_MARKER_FD}
    fi

    _termia_osc133 "B"
}

_termia_precmd() {
    local exit_code=$?

    [[ -n "$TERMIA_NO_RECORD" ]] && { _termia_cmd_id=""; return; }
    if [[ -n "$TERMIA_INTERNAL" ]] && [[ -n "$TERMIA_INTEGRATION_LOADED" ]]; then
        _termia_cmd_id=""; return
    fi
    [[ -z "$_termia_cmd_id" ]] && return

    if [[ -n "$TERMIA_MARKER_FD" ]]; then
        printf '{"cmd_id":"%s","phase":"end","exit_code":%d,"ts":%s}\n' \
            "$_termia_cmd_id" \
            "$exit_code" \
            "${EPOCHREALTIME:-$(date +%s)}" \
            >&${TERMIA_MARKER_FD}
    fi

    _termia_osc133 "D;$exit_code"

    _termia_cmd_id=""
}

# ─── Register hooks ────────────────────────────────────────

autoload -Uz add-zsh-hook
add-zsh-hook preexec _termia_preexec
add-zsh-hook precmd _termia_precmd

_termia_osc133 "A"

# ─── Welcome message (only on first launch) ────────────────

[[ "$TERMIA_WELCOME" == "1" ]] && echo "🚀 Termia active! Type 'tui' for history, 'tai' for AI help."
