# ~/.termia/shell/termia.bash
# Auto-generated by Termia - do not edit manually
# Sourced inside the wrapped shell to provide tui/tai functions and command hooks

# Only activate inside the wrapper
[[ -z "$TERMIA_WRAPPED" ]] && return
[[ -n "$TERMIA_INTEGRATION_LOADED" ]] && return
export TERMIA_INTEGRATION_LOADED=1

# ─── Injected shell functions ───────────────────────────────

tui() {
    local cd_file=""
    if command -v mktemp >/dev/null 2>&1; then
        cd_file="$(mktemp "${TERMIA_SHELL_DIR:-/tmp}/termia-cd.XXXXXX")"
    else
        cd_file="${TERMIA_SHELL_DIR:-/tmp}/termia-cd.$$"
        : >"$cd_file"
    fi
    TERMIA_CD_FILE="$cd_file" "${TERMIA_BIN:-termia}" tui "$@"
    local exit_code=$?
    if [[ -n "$cd_file" && -s "$cd_file" ]]; then
        local new_dir
        new_dir="$(cat "$cd_file")"
        if [[ -n "$new_dir" ]]; then
            builtin cd -- "$new_dir" 2>/dev/null || true
        fi
    fi
    [[ -n "$cd_file" ]] && rm -f "$cd_file"
    return $exit_code
}

tai() {
    "${TERMIA_BIN:-termia}" tai "$@"
}

# ─── Command boundary detection ────────────────────────────
# NOTE: No external dependencies (no jq, no uuidgen).
# Uses pure shell string operations for JSON and ID generation.

_termia_cmd_id=""
_termia_last_cmd=""
_termia_prompt_hint=""
_termia_prompt_base=""

_termia_osc133() {
    local seq="$1"
    printf '\033]133;%s\007' "$seq"
}
# Guard: only record after PROMPT_COMMAND chain fully completes.
# This prevents conda/__conda_activate, oh-my-zsh hooks, and other
# PROMPT_COMMAND entries from being recorded as phantom commands.
# Initialized to "1" so the very first user command is captured.
_termia_preexec_ready=1

_termia_dealias() {
    local cmdline="$1"
    local first="${cmdline%% *}"
    local alias_def

    alias_def=$(alias "$first" 2>/dev/null) || { printf "%s" "$cmdline"; return; }
    alias_def="${alias_def#alias $first=}"         
    alias_def="${alias_def#\'}" 
    alias_def="${alias_def%\'}" 

    if [[ "$alias_def" == "$first"* ]]; then
        local rest="${alias_def#"$first"}"
        if [[ -n "$rest" && "$cmdline" == "$first$rest"* ]]; then
            printf "%s%s" "$first" "${cmdline#"$first$rest"}"
            return
        fi
    fi

    printf "%s" "$cmdline"
}

_termia_update_prompt_hint() {
    local count_file="${TERMIA_PENDING_PROMPTS_COUNT:-}"
    local count=""
    if [[ -n "$count_file" && -f "$count_file" ]]; then
        read -r count < "$count_file"
    fi
    if [[ "$count" =~ ^[0-9]+$ ]] && [[ "$count" -gt 0 ]]; then
        _termia_prompt_hint="🔔${count} "
    else
        _termia_prompt_hint=""
    fi
    if [[ -z "$_termia_prompt_base" ]]; then
        _termia_prompt_base="$PS1"
    fi
    PS1="${_termia_prompt_hint}${_termia_prompt_base}"
}

_termia_import_history_queue() {
    [[ -n "$TERMIA_NO_RECORD" ]] && return
    local queue="${TERMIA_HISTORY_QUEUE:-}"
    [[ -z "$queue" ]] && return
    [[ ! -s "$queue" ]] && return

    local tmp="${queue}.$$"
    if mv "$queue" "$tmp" 2>/dev/null; then
        : > "$queue" 2>/dev/null
    else
        tmp="$queue"
    fi

    local line
    while IFS= read -r line || [[ -n "$line" ]]; do
        history -s -- "$line"
    done < "$tmp"

    if [[ "$tmp" != "$queue" ]]; then
        rm -f "$tmp"
    else
        : > "$queue" 2>/dev/null
    fi
}

# Capture command start (via DEBUG trap)
_termia_debug_trap() {
    [[ -n "$TERMIA_NO_RECORD" ]] && return
    if [[ -n "$TERMIA_INTERNAL" ]] && [[ -n "$TERMIA_INTEGRATION_LOADED" ]]; then
        return
    fi
    if [[ -n "$TERMIA_INTERNAL_PATTERN" ]] && [[ "$BASH_COMMAND" =~ $TERMIA_INTERNAL_PATTERN ]]; then
        return
    fi
    [[ "$BASH_COMMAND" == "_termia_"* ]] && return  # Skip our own functions
    [[ -n "$_termia_cmd_id" ]] && return

    # Only record after PROMPT_COMMAND chain fully completed.
    # This prevents conda, oh-my-zsh, and other framework commands
    # that run inside PROMPT_COMMAND from being recorded.
    [[ "$_termia_preexec_ready" != "1" ]] && return
    _termia_preexec_ready=""

    _termia_cmd_id="${EPOCHREALTIME:-$(date +%s)}-$$-${RANDOM}"
    _termia_last_cmd="$(_termia_dealias "$BASH_COMMAND")"

    if [[ -n "$TERMIA_MARKER_FD" ]]; then
        local escaped_cmd="${_termia_last_cmd//\"/\\\"}"
        printf '{"cmd_id":"%s","phase":"start","command":"%s","cwd":"%s","ts":%s}\n' \
            "$_termia_cmd_id" \
            "$escaped_cmd" \
            "$PWD" \
            "${EPOCHREALTIME:-$(date +%s)}" \
            >&${TERMIA_MARKER_FD}
    fi

    _termia_osc133 "B"
}

# Record command end (via PROMPT_COMMAND)
_termia_prompt_command() {
    local exit_code=$?

    # Immediately disarm preexec so that commands from other PROMPT_COMMAND
    # entries (conda, oh-my-zsh, etc.) that fire DEBUG trap are ignored.
    # It gets re-armed at the END of the full PROMPT_COMMAND chain.
    _termia_preexec_ready=""

    [[ -n "$TERMIA_NO_RECORD" ]] && { _termia_cmd_id=""; _termia_last_cmd=""; return; }
    if [[ -n "$TERMIA_INTERNAL" ]] && [[ -n "$TERMIA_INTEGRATION_LOADED" ]]; then
        unset TERMIA_INTERNAL
        _termia_cmd_id=""
        _termia_last_cmd=""
        return
    fi

    _termia_import_history_queue
    history -a
    history -n

    [[ -z "$_termia_cmd_id" ]] && return

    if [[ -n "$TERMIA_MARKER_FD" ]]; then
        printf '{"cmd_id":"%s","phase":"end","exit_code":%d,"ts":%s}\n' \
            "$_termia_cmd_id" \
            "$exit_code" \
            "${EPOCHREALTIME:-$(date +%s)}" \
            >&${TERMIA_MARKER_FD}
    fi

    _termia_osc133 "D;$exit_code"

    _termia_cmd_id=""
    _termia_last_cmd=""
}

# ─── Register hooks ────────────────────────────────────────

_termia_osc133 "A"

trap '_termia_debug_trap' DEBUG

# Append to existing PROMPT_COMMAND.
# _termia_preexec_ready=1 MUST be the LAST item so that all other
# PROMPT_COMMAND entries (conda, oh-my-zsh, etc.) run first and their
# DEBUG trap firings are ignored by the _termia_preexec_ready guard.
#
# Bash 5+ supports PROMPT_COMMAND as an array. We handle both forms.
_termia_arm_preexec() {
    _termia_update_prompt_hint
    _termia_preexec_ready=1
}

if [[ ${BASH_VERSINFO[0]:-0} -ge 5 ]] && declare -p PROMPT_COMMAND 2>/dev/null | grep -q '^declare -a'; then
    # Array form (bash 5+): prepend our handler, append arming function
    PROMPT_COMMAND=("_termia_prompt_command" "${PROMPT_COMMAND[@]}" "_termia_arm_preexec")
else
    # String form (bash 4 and default): semicolon-separated
    if [[ -z "$PROMPT_COMMAND" ]]; then
        PROMPT_COMMAND='_termia_prompt_command; _termia_arm_preexec'
    else
        PROMPT_COMMAND="_termia_prompt_command; ${PROMPT_COMMAND}; _termia_arm_preexec"
    fi
fi

# ─── Welcome message ───────────────────────────────────────

[[ "$TERMIA_WELCOME" == "1" ]] && echo "🚀 Termia active! Type 'tui' for history, 'tai' for AI help."
